basePath: /
definitions:
  models.Person:
    properties:
      createdAt:
        type: string
      createdBy:
        type: integer
      displayPhoto:
        type: string
      email:
        type: string
      firstName:
        type: string
      gender:
        type: string
      lastLogin:
        type: string
      lastName:
        type: string
      newPassword:
        type: string
      password:
        type: string
      personID:
        type: integer
      phoneNumber:
        type: string
      status:
        type: string
      updatedAt:
        type: string
      updatedBy:
        type: integer
    type: object
host: localhost:9000
info:
  contact:
    email: edsonjaybcarreon@gmail.com
    name: API support
  description: API for the PET application
  title: PET API
  version: "1.0"
paths:
  /change-password:
    patch:
      consumes:
      - application/json
      description: Change the password of the user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Person'
      summary: Change the password of the user
      tags:
      - auth
  /persons:
    get:
      consumes:
      - application/json
      description: Get all users from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Person'
            type: array
      summary: Get all users from the database
      tags:
      - person
  /persons/:id:
    get:
      consumes:
      - application/json
      description: Get user by its ID
      parameters:
      - description: Person ID
        in: path
        name: person_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get a user by its ID
      tags:
      - person
  /signin:
    post:
      consumes:
      - application/json
      description: Signs the user into the application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Person'
      summary: Signs the user into the application
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      description: Signs up the user to the application
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Person'
      summary: Signs up the user to the application
      tags:
      - auth
swagger: "2.0"
